INSERT INTO Role (name, createDate, updateDate) VALUES
                                                    ('ROLE_ADMIN', GETDATE(), GETDATE()),
                                                    ('ROLE_EMPLOYEE', GETDATE(), GETDATE()),
                                                    ('ROLE_USER', GETDATE(), GETDATE());
INSERT INTO Brand (code, name, status, deleteFlag) VALUES
                                                       ('BR01', N'Nike', 1, 0),
                                                       ('BR02', N'Adidas', 1, 0),
                                                       ('BR03', N'Puma', 1, 0),
                                                       ('BR04', N'Vans', 1, 0),
                                                       ('BR05', N'Converse', 1, 0),
                                                       ('BR06', N'New Balance', 1, 0),
                                                       ('BR07', N'Asics', 1, 0),
                                                       ('BR08', N'Reebok', 1, 0),
                                                       ('BR09', N'Under Armour', 1, 0),
                                                       ('BR10', N'Fila', 1, 0);
INSERT INTO Category (code, name, status, deleteFlag) VALUES
                                                          ('CAT01', N'Sneaker', 1, 0),
                                                          ('CAT02', N'Sandal', 1, 0),
                                                          ('CAT03', N'Boot', 1, 0),
                                                          ('CAT04', N'Running', 1, 0),
                                                          ('CAT05', N'Training', 1, 0),
                                                          ('CAT06', N'Slip-on', 1, 0),
                                                          ('CAT07', N'Dep Lào', 1, 0),
                                                          ('CAT08', N'Giày Tây', 1, 0),
                                                          ('CAT09', N'Dep Quai Hậu', 1, 0),
                                                          ('CAT10', N'High Top', 1, 0);
INSERT INTO Color (code, name, deleteFlag) VALUES
                                               ('CL01', N'Đen', 0),
                                               ('CL02', N'Trắng', 0),
                                               ('CL03', N'Xám', 0),
                                               ('CL04', N'Xanh biển', 0),
                                               ('CL05', N'Xanh lá', 0),
                                               ('CL06', N'Đỏ', 0),
                                               ('CL07', N'Vàng', 0),
                                               ('CL08', N'Hồng', 0),
                                               ('CL09', N'Nâu', 0),
                                               ('CL10', N'Tím', 0);
INSERT INTO Material (code, name, status, deleteFlag) VALUES
                                                          ('MT01', N'Da bò', 1, 0),
                                                          ('MT02', N'Da PU', 1, 0),
                                                          ('MT03', N'Da tổng hợp', 1, 0),
                                                          ('MT04', N'Vải Canvas', 1, 0),
                                                          ('MT05', N'Mesh', 1, 0),
                                                          ('MT06', N'Nhựa PVC', 1, 0),
                                                          ('MT07', N'Suede', 1, 0),
                                                          ('MT08', N'Cao su', 1, 0),
                                                          ('MT09', N'Vải Dệt', 1, 0),
                                                          ('MT10', N'Vải Lưới', 1, 0);
INSERT INTO Size (code, name, deleteFlag) VALUES
                                              ('SZ38', N'38', 0),
                                              ('SZ39', N'39', 0),
                                              ('SZ40', N'40', 0),
                                              ('SZ41', N'41', 0),
                                              ('SZ42', N'42', 0),
                                              ('SZ43', N'43', 0),
                                              ('SZ44', N'44', 0),
                                              ('SZ45', N'45', 0),
                                              ('SZ46', N'46', 0),
                                              ('SZ47', N'47', 0);
INSERT INTO Customer (code, name, phoneNumber, email) VALUES
                                                          ('CUST01', N'Nguyễn Văn A', '0900000001', 'a@gmail.com'),
                                                          ('CUST02', N'Trần Thị B', '0900000002', 'b@gmail.com'),
                                                          ('CUST03', N'Lê Văn C', '0900000003', 'c@gmail.com'),
                                                          ('CUST04', N'Phạm Thị D', '0900000004', 'd@gmail.com'),
                                                          ('CUST05', N'Hoàng Văn E', '0900000005', 'e@gmail.com'),
                                                          ('CUST06', N'Đỗ Thị F', '0900000006', 'f@gmail.com'),
                                                          ('CUST07', N'Vũ Văn G', '0900000007', 'g@gmail.com'),
                                                          ('CUST08', N'Ngô Thị H', '0900000008', 'h@gmail.com'),
                                                          ('CUST09', N'Bùi Văn I', '0900000009', 'i@gmail.com'),
                                                          ('CUST10', N'Lý Thị J', '0900000010', 'j@gmail.com');
INSERT INTO Account (code, birthDay, email, password, createDate, updateDate, isNonLocked, customer_id, role_id) VALUES
                                                                                                                     ('ACC01', '1990-01-01', 'a@gmail.com', '123456', GETDATE(), GETDATE(), 1, 1, 1),
                                                                                                                     ('ACC02', '1991-01-01', 'b@gmail.com', '123456', GETDATE(), GETDATE(), 1, 2, 2),
                                                                                                                     ('ACC03', '1992-01-01', 'c@gmail.com', '123456', GETDATE(), GETDATE(), 1, 3, 3),
                                                                                                                     ('ACC04', '1993-01-01', 'd@gmail.com', '123456', GETDATE(), GETDATE(), 1, 4, 1),
                                                                                                                     ('ACC05', '1994-01-01', 'e@gmail.com', '123456', GETDATE(), GETDATE(), 1, 5, 2),
                                                                                                                     ('ACC06', '1995-01-01', 'f@gmail.com', '123456', GETDATE(), GETDATE(), 1, 6, 3),
                                                                                                                     ('ACC07', '1996-01-01', 'g@gmail.com', '123456', GETDATE(), GETDATE(), 1, 7, 1),
                                                                                                                     ('ACC08', '1997-01-01', 'h@gmail.com', '123456', GETDATE(), GETDATE(), 1, 8, 2),
                                                                                                                     ('ACC09', '1998-01-01', 'i@gmail.com', '123456', GETDATE(), GETDATE(), 1, 9, 3),
                                                                                                                     ('ACC10', '1999-01-01', 'j@gmail.com', '123456', GETDATE(), GETDATE(), 1, 10, 1);
INSERT INTO AddressShipping (address, customer_id) VALUES
                                                       (N'123 A đường ABC', 1),
                                                       (N'234 B đường DEF', 2),
                                                       (N'345 C đường XYZ', 3),
                                                       (N'456 D đường LMN', 4),
                                                       (N'567 E đường PQR', 5),
                                                       (N'678 F đường STU', 6),
                                                       (N'789 G đường IJK', 7),
                                                       (N'890 H đường VWX', 8),
                                                       (N'901 I đường MNO', 9),
                                                       (N'012 J đường GHI', 10);
INSERT INTO Product (code, name, description, status, deleteFlag, price, createDate, updatedDate, categoryId, brandId, materialId) VALUES
                                                                                                                                       ('PR01', N'Giày Nike Air', N'Mẫu giày thể thao hot nhất năm', 1, 0, 2500000, GETDATE(), GETDATE(), 1, 1, 1),
                                                                                                                                       ('PR02', N'Giày Adidas Alpha', N'Phong cách trẻ trung, năng động', 1, 0, 2300000, GETDATE(), GETDATE(), 2, 2, 2),
                                                                                                                                       ('PR03', N'Giày Puma Style', N'Êm ái, phù hợp mọi địa hình', 1, 0, 1800000, GETDATE(), GETDATE(), 3, 3, 3),
                                                                                                                                       ('PR04', N'Giày Vans Off', N'Phong cách đường phố', 1, 0, 1500000, GETDATE(), GETDATE(), 4, 4, 4),
                                                                                                                                       ('PR05', N'Giày Converse Chuck', N'Huyền thoại thời trang', 1, 0, 1900000, GETDATE(), GETDATE(), 5, 5, 5),
                                                                                                                                       ('PR06', N'Giày New Balance', N'Mẫu giày chạy bộ cực nhẹ', 1, 0, 2100000, GETDATE(), GETDATE(), 6, 6, 6),
                                                                                                                                       ('PR07', N'Giày Asics Gel', N'Phù hợp dân tập gym', 1, 0, 2000000, GETDATE(), GETDATE(), 7, 7, 7),
                                                                                                                                       ('PR08', N'Giày Reebok Classic', N'Mềm mại và bền bỉ', 1, 0, 1750000, GETDATE(), GETDATE(), 8, 8, 8),
                                                                                                                                       ('PR09', N'Giày UA Charge', N'Phong cách thể thao mạnh mẽ', 1, 0, 1950000, GETDATE(), GETDATE(), 9, 9, 9),
                                                                                                                                       ('PR10', N'Giày Fila Basic', N'Mẫu cổ điển giá rẻ', 1, 0, 1600000, GETDATE(), GETDATE(), 10, 10, 10);
INSERT INTO ProductDetail (quantity, price, barcode, productId, sizeId, colorId) VALUES
                                                                                     (10, 2500000, 'BAR001', 1, 1, 1),
                                                                                     (15, 2300000, 'BAR002', 2, 2, 2),
                                                                                     (8, 1800000, 'BAR003', 3, 3, 3),
                                                                                     (12, 1500000, 'BAR004', 4, 4, 4),
                                                                                     (14, 1900000, 'BAR005', 5, 5, 5),
                                                                                     (9, 2100000, 'BAR006', 6, 6, 6),
                                                                                     (20, 2000000, 'BAR007', 7, 7, 7),
                                                                                     (17, 1750000, 'BAR008', 8, 8, 8),
                                                                                     (11, 1950000, 'BAR009', 9, 9, 9),
                                                                                     (13, 1600000, 'BAR010', 10, 10, 10);
INSERT INTO Image (name, createDate, updateDate, link, fileType, productDetailId) VALUES
                                                                                      (N'Nike Air 1', GETDATE(), GETDATE(), '/uploads/pr01.jpg', 'image/jpeg', 1),
                                                                                      (N'Adidas Alpha 2', GETDATE(), GETDATE(), '/uploads/pr02.jpg', 'image/jpeg', 2),
                                                                                      (N'Puma Style 3', GETDATE(), GETDATE(), '/uploads/pr03.jpg', 'image/jpeg', 3),
                                                                                      (N'Vans Off 4', GETDATE(), GETDATE(), '/uploads/pr04.jpg', 'image/jpeg', 4),
                                                                                      (N'Converse Chuck 5', GETDATE(), GETDATE(), '/uploads/pr05.jpg', 'image/jpeg', 5),
                                                                                      (N'NB Run 6', GETDATE(), GETDATE(), '/uploads/pr06.jpg', 'image/jpeg', 6),
                                                                                      (N'Asics Gym 7', GETDATE(), GETDATE(), '/uploads/pr07.jpg', 'image/jpeg', 7),
                                                                                      (N'Reebok Basic 8', GETDATE(), GETDATE(), '/uploads/pr08.jpg', 'image/jpeg', 8),
                                                                                      (N'UA Sport 9', GETDATE(), GETDATE(), '/uploads/pr09.jpg', 'image/jpeg', 9),
                                                                                      (N'Fila Light 10', GETDATE(), GETDATE(), '/uploads/pr10.jpg', 'image/jpeg', 10);
